---
title: "Read Raw Data"
author: "Rui Nascimento"
date: "`r format(Sys.time(), '%d %B, %Y (%X)')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read Raw Data and save to R objects

Get list of all files in directory

```{r listFiles}
files <- list.files(path="expression/htseq-count/", pattern="_counts")
head(files)
```

Merge the first to files and store

```{r merge1}
file1 <- read.table(paste0("expression/htseq-count/",files[1]), col.names=c("id",tools::file_path_sans_ext(files[1])))
file2 <- read.table(paste0("expression/htseq-count/",files[2]), col.names=c("id",tools::file_path_sans_ext(files[2])))
out.file <- merge (file1, file2, by=c("id"))
```

For loop to merge contents of remaining files

```{r merge2}
for(i in 3:length(files))
{
  file <-  read.table(paste0("expression/htseq-count/",files[i]),col.names=c("id",tools::file_path_sans_ext(files[i])))
  out.file <- merge(out.file, file, by=c("id"))
}
```

Save Raw Merged Dataset

```{r saveTable}
write.table(out.file, file = paste0("expression/htseq-count/", "htseq_all_sample_count.tsv"),sep="\t", row.names = FALSE)
```

Prepare dataset for the rest of the analysis and save the .RDS

```{r saveRDS}
out.file<-out.file[!grepl("__no_feature", out.file$id),]
out.file<-out.file[!grepl("__ambiguous", out.file$id),]
out.file<-out.file[!grepl("__too_low_aQual", out.file$id),]
out.file<-out.file[!grepl("__not_aligned", out.file$id),]
out.file<-out.file[!grepl("__alignment_not_unique", out.file$id),]

saveRDS(out.file, file = "data/out.file.RDS")
```